# See the dedicated "version" documentation section.
version: "2"
linters:
  default: all
  disable:
    # Deprecated
    - gomodguard
    - wsl

    # We don't care about line length or whitespace
    - lll
    - whitespace
    - nlreturn
    - nakedret

    - wsl_v5

    # No sorting needed
    - funcorder

    # Comments and task lists
    - godox
    - godot

    # Magic numbers in a lot of binary places
    - mnd
    - goconst

    # No wrap checks
    - wrapcheck

    # General or pedantic ones
    - nonamedreturns
    - noinlineerr
    - exhaustruct

    # Complexity and duplicity is fine
    - interfacebloat
    - nestif
    - gocognit
    - gocyclo
    - cyclop
    - maintidx
    - funlen
    # Or too little complexity
    - varnamelen

    # TODO: enable these after cleanup or nolint
    - err113
    - gochecknoglobals

  settings:
    tagliatelle:
      case:
        rules:
          json: snake
        overrides:
          # Monero ZMQ and RPC naming are a mess
          - pkg: "monero/client/zmq"
            ignore: true
          - pkg: "monero/client/rpc/daemon"
            ignore: true

    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - ifElseChain
        - commentFormatting
        - sloppyReassign
        - appendAssign
        - captLocal
        - commentedOutCode
    revive:
      rules:
        - name: atomic
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: call-to-gc
        - name: constant-logical-expr
        - name: datarace
        - name: deep-exit
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: get-return
        - name: identical-branches
        - name: identical-ifelseif-branches
        - name: identical-ifelseif-conditions
        - name: identical-switch-branches
        - name: identical-switch-conditions
        - name: increment-decrement
        - name: inefficient-map-lookup
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: optimize-operands-order
        - name: package-directory-mismatch
        - name: redefines-builtin-id
        - name: redundant-build-tag
        - name: redundant-import-alias
        - name: string-of-int
        - name: struct-tag
        - name: time-date
        - name: time-equal
        - name: unchecked-type-assertion
        - name: unconditional-recursion
        - name: unexported-return
        - name: unnecessary-if
        - name: unnecessary-format
        - name: use-any
        - name: use-fmt-print
        - name: use-slices-sort
        - name: waitgroup-by-value


    ireturn:
      allow:
        - stdlib
        - error
        - generic
        - "git.gammaspectra.live/P2Pool/consensus/v5/monero/randomx.Hasher"
        - "git.gammaspectra.live/P2Pool/consensus/v5/monero/transaction.Proofs"
        - "git.gammaspectra.live/P2Pool/consensus/v5/monero/transaction.Transaction"
        - "git.gammaspectra.live/P2Pool/consensus/v5/monero/transaction.PrunedTransaction"

    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        # no condition De Morgan's law
        - "-QF1001"
        - "-QF1003"

    gosec:
      excludes:
        # integer overflow conversion
        # todo: too noisy, too prevalent, can't configure specific safe conversions like to int
        - G115

    errcheck:
      exclude-functions:
        - "io.ReadAll"
        - "(io.ReadCloser).Close"
        - "(net.Conn).Close"
        - "(*net.TCPConn).Close"
        - "(*net.conn).Close"
        - "(*net.TCPListener).Close"

    forbidigo:
      forbid:
        - pattern: ^print(ln)?$
        - pattern: ^fmt\.Print.*$

        # noescape concerns
        - pattern: ^io.ReadFull$
          msg: Use utils.ReadFullNoEscape
        - pattern: ^binary.Read$
          msg: Use utils.BinaryReadNoEscape

        # varint consensus / malleability related
        - pattern: ^binary.ReadUvarint$
          msg: Use utils.ReadCanonicalUvarint
        - pattern: ^binary.ReadVarint$
          msg: Use utils.ReadCanonicalUvarint
        - pattern: ^binary.Uvarint$
          msg: Use utils.CanonicalUvarint
        - pattern: ^binary.Varint$
          msg: Use utils.CanonicalUvarint

        # test crypto
        - pattern: ^crypto.NewDeterministicTestGenerator$
          msg: Test-only cryptography
        - pattern: ^curve25519.RandomPoint$
          msg: Test-only cryptography

      analyze-types: true

    depguard:
      rules:
        deprecated:
          list-mode: lax
          deny:
            - pkg: "ioutil"
              desc: use io
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "encoding/json$"
              desc: use utils JSON
            - pkg: "git.gammaspectra.live/P2Pool/go-json$"
              desc: use utils JSON
            - pkg: "encoding/hex"
              desc: use git.gammaspectra.live/P2Pool/go-hex
            - pkg: "golang.org/x/crypto/blake2b"
              desc: use git.gammaspectra.live/P2Pool/blake2b
            - pkg: "golang.org/x/crypto/sha3"
              desc: use monero/crypto/NewKeccak256 or monero/crypto/sha3
            - pkg: "crypto/sha3"
              desc: use monero/crypto/NewKeccak256 or monero/crypto/sha3
        unsafeRandom:
          list-mode: lax
          deny:
            - pkg: "math/rand/v2$"
              desc: use crypto/rand
        curve25519:
          list-mode: lax
          deny:
            - pkg: "git.gammaspectra.live/P2Pool/edwards25519"
              desc: use monero/crypto/curve25519
        helioselene:
          list-mode: lax
          deny:
            - pkg: "git.gammaspectra.live/P2Pool/helioselene"
              desc: use monero/crypto/helioselene

formatters:
  enable:
    - gofmt
    - goimports

severity:
  default: error

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

output:

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly
  go: "1.26"