# See the dedicated "version" documentation section.
version: "2"
linters:
  default: all
  disable:
    # We don't care about line length or whitespace
    - lll
    - whitespace
    - nlreturn
    - nakedret

    - wsl
    - wsl_v5

    # Inconsistent across the project due to Monero/Go contexts
    - tagliatelle

    # No sorting needed
    - funcorder

    # Comments and task lists
    - godox
    - godot

    # Magic numbers in a lot of binary places
    - mnd

    # No wrap checks
    - wrapcheck

    # General or pedantic ones
    - revive
    - nonamedreturns
    - noinlineerr
    - gocritic
    - exhaustruct
    - ireturn
    - goconst
    - forcetypeassert

    # Complexity and duplicity is fine
    - interfacebloat
    - nestif
    - gocognit
    - gocyclo
    - cyclop
    - maintidx
    - funlen
    - dupl
    # Or too little complexity
    - varnamelen

    # TODO: enable these after cleanup or nolint
    - err113
    - gochecknoglobals

  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
        - "-ST1003"
        - "-ST1020"
        - "-ST1022"
        # no condition De Morgan's law
        - "-QF1001"
        - "-QF1003"

    gosec:
      excludes:
        # secrets in code
        # todo: define rules to ignore existing
        - G101
        # unsafe calls should be audited
        # todo: explicitly tag each one
        - G103
        # integer overflow conversion
        # todo: too noisy, too prevalent, can't configure specific safe conversions like to int
        - G115

    errcheck:
      exclude-functions:
        - "io.ReadAll"
        - "(io.ReadCloser).Close"
        - "(net.Conn).Close"
        - "(*net.TCPConn).Close"
        - "(*net.conn).Close"
        - "(*net.TCPListener).Close"

    depguard:
      rules:
        main:
          list-mode: lax
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "encoding/json$"
              desc: use git.gammaspectra.live/P2Pool/go-json
        unsafeRandom:
          list-mode: lax
          deny:
            - pkg: "math/rand/v2$"
              desc: use crypto/rand
        curve25519:
          list-mode: lax
          deny:
            - pkg: "git.gammaspectra.live/P2Pool/edwards25519"
              desc: use monero/crypto/curve25519
  exclusions:
    rules:

    paths:
      - "monero/client/levin/*"


severity:
  default: error

issues:


output:

run:
  timeout: 5m
  tests: false
  modules-download-mode: readonly
  go: "1.25"