version: "2.2"

networks:
  p2pool-observer:
    external: false

volumes:
  db:
    external: false

services:
  db:
    image: postgres:15.2
    restart: always
    read_only: true
    shm_size: 4gb
    security_opt:
      - no-new-privileges:true
    environment:
      - POSTGRES_USER=p2pool
      - POSTGRES_PASSWORD=p2pool
      - POSTGRES_DB=p2pool
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "temp_buffers=32MB"
      - "-c"
      - "hash_mem_multiplier=2.0"
    networks:
      - p2pool-observer
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname \"postgres://p2pool:p2pool@db/p2pool\"" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data:rw
    tmpfs:
      # For read-only filesystem, need to create a volume/tmpfs for PostgreSQL to run its much
      # needed configuration. The read-only flag does not make volumes and tmpfs read-only.
      - /tmp
      - /run
      - /run/postgresql