// Code generated by command: go run keccakf_x4_amd64_asm.go -out ../keccakf_x4_amd64.s. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func KeccakF1600x4(a *[100]uint64)
// Requires: AVX, AVX2
TEXT ·KeccakF1600x4(SB), NOSPLIT, $0-8
	MOVQ a+0(FP), AX
	LEAQ rc<>+0(SB), CX
	MOVQ $0x0000000000000006, DX

loop:
	VMOVDQU      (AX), Y0
	VMOVDQU      32(AX), Y1
	VMOVDQU      64(AX), Y2
	VMOVDQU      96(AX), Y3
	VMOVDQU      128(AX), Y4
	VPXOR        160(AX), Y0, Y0
	VPXOR        192(AX), Y1, Y1
	VPXOR        224(AX), Y2, Y2
	VPXOR        256(AX), Y3, Y3
	VPXOR        288(AX), Y4, Y4
	VPXOR        320(AX), Y0, Y0
	VPXOR        352(AX), Y1, Y1
	VPXOR        384(AX), Y2, Y2
	VPXOR        416(AX), Y3, Y3
	VPXOR        448(AX), Y4, Y4
	VPXOR        480(AX), Y0, Y0
	VPXOR        512(AX), Y1, Y1
	VPXOR        544(AX), Y2, Y2
	VPXOR        576(AX), Y3, Y3
	VPXOR        608(AX), Y4, Y4
	VPXOR        640(AX), Y0, Y0
	VPXOR        672(AX), Y1, Y1
	VPXOR        704(AX), Y2, Y2
	VPXOR        736(AX), Y3, Y3
	VPXOR        768(AX), Y4, Y4
	VPSLLQ       $0x01, Y1, Y5
	VPSLLQ       $0x01, Y2, Y6
	VPSLLQ       $0x01, Y3, Y7
	VPSLLQ       $0x01, Y4, Y8
	VPSLLQ       $0x01, Y0, Y9
	VPSRLQ       $0x3f, Y1, Y10
	VPSRLQ       $0x3f, Y2, Y11
	VPSRLQ       $0x3f, Y3, Y12
	VPSRLQ       $0x3f, Y4, Y13
	VPSRLQ       $0x3f, Y0, Y14
	VPOR         Y5, Y10, Y10
	VPOR         Y6, Y11, Y11
	VPOR         Y7, Y12, Y12
	VPOR         Y8, Y13, Y13
	VPOR         Y9, Y14, Y14
	VPXOR        Y10, Y4, Y10
	VPXOR        Y11, Y0, Y11
	VPXOR        Y12, Y1, Y12
	VPXOR        Y13, Y2, Y13
	VPXOR        Y14, Y3, Y14
	VPXOR        (AX), Y10, Y0
	VPXOR        192(AX), Y11, Y1
	VPXOR        384(AX), Y12, Y2
	VPXOR        576(AX), Y13, Y3
	VPXOR        768(AX), Y14, Y4
	VPSLLQ       $0x2c, Y1, Y6
	VPSLLQ       $0x2b, Y2, Y7
	VPSLLQ       $0x15, Y3, Y8
	VPSLLQ       $0x0e, Y4, Y9
	VPSRLQ       $0x14, Y1, Y1
	VPSRLQ       $0x15, Y2, Y2
	VPSRLQ       $0x2b, Y3, Y3
	VPSRLQ       $0x32, Y4, Y4
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VPBROADCASTQ (CX), Y0
	VPXOR        Y0, Y5, Y5
	VMOVDQU      Y5, (AX)
	VMOVDQU      Y6, 192(AX)
	VMOVDQU      Y7, 384(AX)
	VMOVDQU      Y8, 576(AX)
	VMOVDQU      Y9, 768(AX)
	VPXOR        96(AX), Y13, Y0
	VPXOR        288(AX), Y14, Y1
	VPXOR        320(AX), Y10, Y2
	VPXOR        512(AX), Y11, Y3
	VPXOR        704(AX), Y12, Y4
	VPSLLQ       $0x1c, Y0, Y5
	VPSLLQ       $0x14, Y1, Y6
	VPSLLQ       $0x03, Y2, Y7
	VPSLLQ       $0x2d, Y3, Y8
	VPSLLQ       $0x3d, Y4, Y9
	VPSRLQ       $0x24, Y0, Y0
	VPSRLQ       $0x2c, Y1, Y1
	VPSRLQ       $0x3d, Y2, Y2
	VPSRLQ       $0x13, Y3, Y3
	VPSRLQ       $0x03, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 320(AX)
	VMOVDQU      Y6, 512(AX)
	VMOVDQU      Y7, 704(AX)
	VMOVDQU      Y8, 96(AX)
	VMOVDQU      Y9, 288(AX)
	VPXOR        32(AX), Y11, Y0
	VPXOR        224(AX), Y12, Y1
	VPXOR        416(AX), Y13, Y2
	VPXOR        608(AX), Y14, Y3
	VPXOR        640(AX), Y10, Y4
	VPSLLQ       $0x01, Y0, Y5
	VPSLLQ       $0x06, Y1, Y6
	VPSLLQ       $0x19, Y2, Y7
	VPSLLQ       $0x08, Y3, Y8
	VPSLLQ       $0x12, Y4, Y9
	VPSRLQ       $0x3f, Y0, Y0
	VPSRLQ       $0x3a, Y1, Y1
	VPSRLQ       $0x27, Y2, Y2
	VPSRLQ       $0x38, Y3, Y3
	VPSRLQ       $0x2e, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 640(AX)
	VMOVDQU      Y6, 32(AX)
	VMOVDQU      Y7, 224(AX)
	VMOVDQU      Y8, 416(AX)
	VMOVDQU      Y9, 608(AX)
	VPXOR        128(AX), Y14, Y0
	VPXOR        160(AX), Y10, Y1
	VPXOR        352(AX), Y11, Y2
	VPXOR        544(AX), Y12, Y3
	VPXOR        736(AX), Y13, Y4
	VPSLLQ       $0x1b, Y0, Y5
	VPSLLQ       $0x24, Y1, Y6
	VPSLLQ       $0x0a, Y2, Y7
	VPSLLQ       $0x0f, Y3, Y8
	VPSLLQ       $0x38, Y4, Y9
	VPSRLQ       $0x25, Y0, Y0
	VPSRLQ       $0x1c, Y1, Y1
	VPSRLQ       $0x36, Y2, Y2
	VPSRLQ       $0x31, Y3, Y3
	VPSRLQ       $0x08, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 160(AX)
	VMOVDQU      Y6, 352(AX)
	VMOVDQU      Y7, 544(AX)
	VMOVDQU      Y8, 736(AX)
	VMOVDQU      Y9, 128(AX)
	VPXOR        64(AX), Y12, Y0
	VPXOR        256(AX), Y13, Y1
	VPXOR        448(AX), Y14, Y2
	VPXOR        480(AX), Y10, Y3
	VPXOR        672(AX), Y11, Y4
	VPSLLQ       $0x3e, Y0, Y5
	VPSLLQ       $0x37, Y1, Y6
	VPSLLQ       $0x27, Y2, Y7
	VPSLLQ       $0x29, Y3, Y8
	VPSLLQ       $0x02, Y4, Y9
	VPSRLQ       $0x02, Y0, Y0
	VPSRLQ       $0x09, Y1, Y1
	VPSRLQ       $0x19, Y2, Y2
	VPSRLQ       $0x17, Y3, Y3
	VPSRLQ       $0x3e, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 480(AX)
	VMOVDQU      Y6, 672(AX)
	VMOVDQU      Y7, 64(AX)
	VMOVDQU      Y8, 256(AX)
	VMOVDQU      Y9, 448(AX)
	VMOVDQU      (AX), Y0
	VMOVDQU      32(AX), Y1
	VMOVDQU      64(AX), Y2
	VMOVDQU      96(AX), Y3
	VMOVDQU      128(AX), Y4
	VPXOR        160(AX), Y0, Y0
	VPXOR        192(AX), Y1, Y1
	VPXOR        224(AX), Y2, Y2
	VPXOR        256(AX), Y3, Y3
	VPXOR        288(AX), Y4, Y4
	VPXOR        320(AX), Y0, Y0
	VPXOR        352(AX), Y1, Y1
	VPXOR        384(AX), Y2, Y2
	VPXOR        416(AX), Y3, Y3
	VPXOR        448(AX), Y4, Y4
	VPXOR        480(AX), Y0, Y0
	VPXOR        512(AX), Y1, Y1
	VPXOR        544(AX), Y2, Y2
	VPXOR        576(AX), Y3, Y3
	VPXOR        608(AX), Y4, Y4
	VPXOR        640(AX), Y0, Y0
	VPXOR        672(AX), Y1, Y1
	VPXOR        704(AX), Y2, Y2
	VPXOR        736(AX), Y3, Y3
	VPXOR        768(AX), Y4, Y4
	VPSLLQ       $0x01, Y1, Y5
	VPSLLQ       $0x01, Y2, Y6
	VPSLLQ       $0x01, Y3, Y7
	VPSLLQ       $0x01, Y4, Y8
	VPSLLQ       $0x01, Y0, Y9
	VPSRLQ       $0x3f, Y1, Y10
	VPSRLQ       $0x3f, Y2, Y11
	VPSRLQ       $0x3f, Y3, Y12
	VPSRLQ       $0x3f, Y4, Y13
	VPSRLQ       $0x3f, Y0, Y14
	VPOR         Y5, Y10, Y10
	VPOR         Y6, Y11, Y11
	VPOR         Y7, Y12, Y12
	VPOR         Y8, Y13, Y13
	VPOR         Y9, Y14, Y14
	VPXOR        Y10, Y4, Y10
	VPXOR        Y11, Y0, Y11
	VPXOR        Y12, Y1, Y12
	VPXOR        Y13, Y2, Y13
	VPXOR        Y14, Y3, Y14
	VPXOR        (AX), Y10, Y0
	VPXOR        512(AX), Y11, Y1
	VPXOR        224(AX), Y12, Y2
	VPXOR        736(AX), Y13, Y3
	VPXOR        448(AX), Y14, Y4
	VPSLLQ       $0x2c, Y1, Y6
	VPSLLQ       $0x2b, Y2, Y7
	VPSLLQ       $0x15, Y3, Y8
	VPSLLQ       $0x0e, Y4, Y9
	VPSRLQ       $0x14, Y1, Y1
	VPSRLQ       $0x15, Y2, Y2
	VPSRLQ       $0x2b, Y3, Y3
	VPSRLQ       $0x32, Y4, Y4
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VPBROADCASTQ 8(CX), Y0
	VPXOR        Y0, Y5, Y5
	VMOVDQU      Y5, (AX)
	VMOVDQU      Y6, 512(AX)
	VMOVDQU      Y7, 224(AX)
	VMOVDQU      Y8, 736(AX)
	VMOVDQU      Y9, 448(AX)
	VPXOR        576(AX), Y13, Y0
	VPXOR        288(AX), Y14, Y1
	VPXOR        640(AX), Y10, Y2
	VPXOR        352(AX), Y11, Y3
	VPXOR        64(AX), Y12, Y4
	VPSLLQ       $0x1c, Y0, Y5
	VPSLLQ       $0x14, Y1, Y6
	VPSLLQ       $0x03, Y2, Y7
	VPSLLQ       $0x2d, Y3, Y8
	VPSLLQ       $0x3d, Y4, Y9
	VPSRLQ       $0x24, Y0, Y0
	VPSRLQ       $0x2c, Y1, Y1
	VPSRLQ       $0x3d, Y2, Y2
	VPSRLQ       $0x13, Y3, Y3
	VPSRLQ       $0x03, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 640(AX)
	VMOVDQU      Y6, 352(AX)
	VMOVDQU      Y7, 64(AX)
	VMOVDQU      Y8, 576(AX)
	VMOVDQU      Y9, 288(AX)
	VPXOR        192(AX), Y11, Y0
	VPXOR        704(AX), Y12, Y1
	VPXOR        416(AX), Y13, Y2
	VPXOR        128(AX), Y14, Y3
	VPXOR        480(AX), Y10, Y4
	VPSLLQ       $0x01, Y0, Y5
	VPSLLQ       $0x06, Y1, Y6
	VPSLLQ       $0x19, Y2, Y7
	VPSLLQ       $0x08, Y3, Y8
	VPSLLQ       $0x12, Y4, Y9
	VPSRLQ       $0x3f, Y0, Y0
	VPSRLQ       $0x3a, Y1, Y1
	VPSRLQ       $0x27, Y2, Y2
	VPSRLQ       $0x38, Y3, Y3
	VPSRLQ       $0x2e, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 480(AX)
	VMOVDQU      Y6, 192(AX)
	VMOVDQU      Y7, 704(AX)
	VMOVDQU      Y8, 416(AX)
	VMOVDQU      Y9, 128(AX)
	VPXOR        768(AX), Y14, Y0
	VPXOR        320(AX), Y10, Y1
	VPXOR        32(AX), Y11, Y2
	VPXOR        544(AX), Y12, Y3
	VPXOR        256(AX), Y13, Y4
	VPSLLQ       $0x1b, Y0, Y5
	VPSLLQ       $0x24, Y1, Y6
	VPSLLQ       $0x0a, Y2, Y7
	VPSLLQ       $0x0f, Y3, Y8
	VPSLLQ       $0x38, Y4, Y9
	VPSRLQ       $0x25, Y0, Y0
	VPSRLQ       $0x1c, Y1, Y1
	VPSRLQ       $0x36, Y2, Y2
	VPSRLQ       $0x31, Y3, Y3
	VPSRLQ       $0x08, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 320(AX)
	VMOVDQU      Y6, 32(AX)
	VMOVDQU      Y7, 544(AX)
	VMOVDQU      Y8, 256(AX)
	VMOVDQU      Y9, 768(AX)
	VPXOR        384(AX), Y12, Y0
	VPXOR        96(AX), Y13, Y1
	VPXOR        608(AX), Y14, Y2
	VPXOR        160(AX), Y10, Y3
	VPXOR        672(AX), Y11, Y4
	VPSLLQ       $0x3e, Y0, Y5
	VPSLLQ       $0x37, Y1, Y6
	VPSLLQ       $0x27, Y2, Y7
	VPSLLQ       $0x29, Y3, Y8
	VPSLLQ       $0x02, Y4, Y9
	VPSRLQ       $0x02, Y0, Y0
	VPSRLQ       $0x09, Y1, Y1
	VPSRLQ       $0x19, Y2, Y2
	VPSRLQ       $0x17, Y3, Y3
	VPSRLQ       $0x3e, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 160(AX)
	VMOVDQU      Y6, 672(AX)
	VMOVDQU      Y7, 384(AX)
	VMOVDQU      Y8, 96(AX)
	VMOVDQU      Y9, 608(AX)
	VMOVDQU      (AX), Y0
	VMOVDQU      32(AX), Y1
	VMOVDQU      64(AX), Y2
	VMOVDQU      96(AX), Y3
	VMOVDQU      128(AX), Y4
	VPXOR        160(AX), Y0, Y0
	VPXOR        192(AX), Y1, Y1
	VPXOR        224(AX), Y2, Y2
	VPXOR        256(AX), Y3, Y3
	VPXOR        288(AX), Y4, Y4
	VPXOR        320(AX), Y0, Y0
	VPXOR        352(AX), Y1, Y1
	VPXOR        384(AX), Y2, Y2
	VPXOR        416(AX), Y3, Y3
	VPXOR        448(AX), Y4, Y4
	VPXOR        480(AX), Y0, Y0
	VPXOR        512(AX), Y1, Y1
	VPXOR        544(AX), Y2, Y2
	VPXOR        576(AX), Y3, Y3
	VPXOR        608(AX), Y4, Y4
	VPXOR        640(AX), Y0, Y0
	VPXOR        672(AX), Y1, Y1
	VPXOR        704(AX), Y2, Y2
	VPXOR        736(AX), Y3, Y3
	VPXOR        768(AX), Y4, Y4
	VPSLLQ       $0x01, Y1, Y5
	VPSLLQ       $0x01, Y2, Y6
	VPSLLQ       $0x01, Y3, Y7
	VPSLLQ       $0x01, Y4, Y8
	VPSLLQ       $0x01, Y0, Y9
	VPSRLQ       $0x3f, Y1, Y10
	VPSRLQ       $0x3f, Y2, Y11
	VPSRLQ       $0x3f, Y3, Y12
	VPSRLQ       $0x3f, Y4, Y13
	VPSRLQ       $0x3f, Y0, Y14
	VPOR         Y5, Y10, Y10
	VPOR         Y6, Y11, Y11
	VPOR         Y7, Y12, Y12
	VPOR         Y8, Y13, Y13
	VPOR         Y9, Y14, Y14
	VPXOR        Y10, Y4, Y10
	VPXOR        Y11, Y0, Y11
	VPXOR        Y12, Y1, Y12
	VPXOR        Y13, Y2, Y13
	VPXOR        Y14, Y3, Y14
	VPXOR        (AX), Y10, Y0
	VPXOR        352(AX), Y11, Y1
	VPXOR        704(AX), Y12, Y2
	VPXOR        256(AX), Y13, Y3
	VPXOR        608(AX), Y14, Y4
	VPSLLQ       $0x2c, Y1, Y6
	VPSLLQ       $0x2b, Y2, Y7
	VPSLLQ       $0x15, Y3, Y8
	VPSLLQ       $0x0e, Y4, Y9
	VPSRLQ       $0x14, Y1, Y1
	VPSRLQ       $0x15, Y2, Y2
	VPSRLQ       $0x2b, Y3, Y3
	VPSRLQ       $0x32, Y4, Y4
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VPBROADCASTQ 16(CX), Y0
	VPXOR        Y0, Y5, Y5
	VMOVDQU      Y5, (AX)
	VMOVDQU      Y6, 352(AX)
	VMOVDQU      Y7, 704(AX)
	VMOVDQU      Y8, 256(AX)
	VMOVDQU      Y9, 608(AX)
	VPXOR        736(AX), Y13, Y0
	VPXOR        288(AX), Y14, Y1
	VPXOR        480(AX), Y10, Y2
	VPXOR        32(AX), Y11, Y3
	VPXOR        384(AX), Y12, Y4
	VPSLLQ       $0x1c, Y0, Y5
	VPSLLQ       $0x14, Y1, Y6
	VPSLLQ       $0x03, Y2, Y7
	VPSLLQ       $0x2d, Y3, Y8
	VPSLLQ       $0x3d, Y4, Y9
	VPSRLQ       $0x24, Y0, Y0
	VPSRLQ       $0x2c, Y1, Y1
	VPSRLQ       $0x3d, Y2, Y2
	VPSRLQ       $0x13, Y3, Y3
	VPSRLQ       $0x03, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 480(AX)
	VMOVDQU      Y6, 32(AX)
	VMOVDQU      Y7, 384(AX)
	VMOVDQU      Y8, 736(AX)
	VMOVDQU      Y9, 288(AX)
	VPXOR        512(AX), Y11, Y0
	VPXOR        64(AX), Y12, Y1
	VPXOR        416(AX), Y13, Y2
	VPXOR        768(AX), Y14, Y3
	VPXOR        160(AX), Y10, Y4
	VPSLLQ       $0x01, Y0, Y5
	VPSLLQ       $0x06, Y1, Y6
	VPSLLQ       $0x19, Y2, Y7
	VPSLLQ       $0x08, Y3, Y8
	VPSLLQ       $0x12, Y4, Y9
	VPSRLQ       $0x3f, Y0, Y0
	VPSRLQ       $0x3a, Y1, Y1
	VPSRLQ       $0x27, Y2, Y2
	VPSRLQ       $0x38, Y3, Y3
	VPSRLQ       $0x2e, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 160(AX)
	VMOVDQU      Y6, 512(AX)
	VMOVDQU      Y7, 64(AX)
	VMOVDQU      Y8, 416(AX)
	VMOVDQU      Y9, 768(AX)
	VPXOR        448(AX), Y14, Y0
	VPXOR        640(AX), Y10, Y1
	VPXOR        192(AX), Y11, Y2
	VPXOR        544(AX), Y12, Y3
	VPXOR        96(AX), Y13, Y4
	VPSLLQ       $0x1b, Y0, Y5
	VPSLLQ       $0x24, Y1, Y6
	VPSLLQ       $0x0a, Y2, Y7
	VPSLLQ       $0x0f, Y3, Y8
	VPSLLQ       $0x38, Y4, Y9
	VPSRLQ       $0x25, Y0, Y0
	VPSRLQ       $0x1c, Y1, Y1
	VPSRLQ       $0x36, Y2, Y2
	VPSRLQ       $0x31, Y3, Y3
	VPSRLQ       $0x08, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 640(AX)
	VMOVDQU      Y6, 192(AX)
	VMOVDQU      Y7, 544(AX)
	VMOVDQU      Y8, 96(AX)
	VMOVDQU      Y9, 448(AX)
	VPXOR        224(AX), Y12, Y0
	VPXOR        576(AX), Y13, Y1
	VPXOR        128(AX), Y14, Y2
	VPXOR        320(AX), Y10, Y3
	VPXOR        672(AX), Y11, Y4
	VPSLLQ       $0x3e, Y0, Y5
	VPSLLQ       $0x37, Y1, Y6
	VPSLLQ       $0x27, Y2, Y7
	VPSLLQ       $0x29, Y3, Y8
	VPSLLQ       $0x02, Y4, Y9
	VPSRLQ       $0x02, Y0, Y0
	VPSRLQ       $0x09, Y1, Y1
	VPSRLQ       $0x19, Y2, Y2
	VPSRLQ       $0x17, Y3, Y3
	VPSRLQ       $0x3e, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 320(AX)
	VMOVDQU      Y6, 672(AX)
	VMOVDQU      Y7, 224(AX)
	VMOVDQU      Y8, 576(AX)
	VMOVDQU      Y9, 128(AX)
	VMOVDQU      (AX), Y0
	VMOVDQU      32(AX), Y1
	VMOVDQU      64(AX), Y2
	VMOVDQU      96(AX), Y3
	VMOVDQU      128(AX), Y4
	VPXOR        160(AX), Y0, Y0
	VPXOR        192(AX), Y1, Y1
	VPXOR        224(AX), Y2, Y2
	VPXOR        256(AX), Y3, Y3
	VPXOR        288(AX), Y4, Y4
	VPXOR        320(AX), Y0, Y0
	VPXOR        352(AX), Y1, Y1
	VPXOR        384(AX), Y2, Y2
	VPXOR        416(AX), Y3, Y3
	VPXOR        448(AX), Y4, Y4
	VPXOR        480(AX), Y0, Y0
	VPXOR        512(AX), Y1, Y1
	VPXOR        544(AX), Y2, Y2
	VPXOR        576(AX), Y3, Y3
	VPXOR        608(AX), Y4, Y4
	VPXOR        640(AX), Y0, Y0
	VPXOR        672(AX), Y1, Y1
	VPXOR        704(AX), Y2, Y2
	VPXOR        736(AX), Y3, Y3
	VPXOR        768(AX), Y4, Y4
	VPSLLQ       $0x01, Y1, Y5
	VPSLLQ       $0x01, Y2, Y6
	VPSLLQ       $0x01, Y3, Y7
	VPSLLQ       $0x01, Y4, Y8
	VPSLLQ       $0x01, Y0, Y9
	VPSRLQ       $0x3f, Y1, Y10
	VPSRLQ       $0x3f, Y2, Y11
	VPSRLQ       $0x3f, Y3, Y12
	VPSRLQ       $0x3f, Y4, Y13
	VPSRLQ       $0x3f, Y0, Y14
	VPOR         Y5, Y10, Y10
	VPOR         Y6, Y11, Y11
	VPOR         Y7, Y12, Y12
	VPOR         Y8, Y13, Y13
	VPOR         Y9, Y14, Y14
	VPXOR        Y10, Y4, Y10
	VPXOR        Y11, Y0, Y11
	VPXOR        Y12, Y1, Y12
	VPXOR        Y13, Y2, Y13
	VPXOR        Y14, Y3, Y14
	VPXOR        (AX), Y10, Y0
	VPXOR        32(AX), Y11, Y1
	VPXOR        64(AX), Y12, Y2
	VPXOR        96(AX), Y13, Y3
	VPXOR        128(AX), Y14, Y4
	VPSLLQ       $0x2c, Y1, Y6
	VPSLLQ       $0x2b, Y2, Y7
	VPSLLQ       $0x15, Y3, Y8
	VPSLLQ       $0x0e, Y4, Y9
	VPSRLQ       $0x14, Y1, Y1
	VPSRLQ       $0x15, Y2, Y2
	VPSRLQ       $0x2b, Y3, Y3
	VPSRLQ       $0x32, Y4, Y4
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VPBROADCASTQ 24(CX), Y0
	VPXOR        Y0, Y5, Y5
	VMOVDQU      Y5, (AX)
	VMOVDQU      Y6, 32(AX)
	VMOVDQU      Y7, 64(AX)
	VMOVDQU      Y8, 96(AX)
	VMOVDQU      Y9, 128(AX)
	VPXOR        256(AX), Y13, Y0
	VPXOR        288(AX), Y14, Y1
	VPXOR        160(AX), Y10, Y2
	VPXOR        192(AX), Y11, Y3
	VPXOR        224(AX), Y12, Y4
	VPSLLQ       $0x1c, Y0, Y5
	VPSLLQ       $0x14, Y1, Y6
	VPSLLQ       $0x03, Y2, Y7
	VPSLLQ       $0x2d, Y3, Y8
	VPSLLQ       $0x3d, Y4, Y9
	VPSRLQ       $0x24, Y0, Y0
	VPSRLQ       $0x2c, Y1, Y1
	VPSRLQ       $0x3d, Y2, Y2
	VPSRLQ       $0x13, Y3, Y3
	VPSRLQ       $0x03, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 160(AX)
	VMOVDQU      Y6, 192(AX)
	VMOVDQU      Y7, 224(AX)
	VMOVDQU      Y8, 256(AX)
	VMOVDQU      Y9, 288(AX)
	VPXOR        352(AX), Y11, Y0
	VPXOR        384(AX), Y12, Y1
	VPXOR        416(AX), Y13, Y2
	VPXOR        448(AX), Y14, Y3
	VPXOR        320(AX), Y10, Y4
	VPSLLQ       $0x01, Y0, Y5
	VPSLLQ       $0x06, Y1, Y6
	VPSLLQ       $0x19, Y2, Y7
	VPSLLQ       $0x08, Y3, Y8
	VPSLLQ       $0x12, Y4, Y9
	VPSRLQ       $0x3f, Y0, Y0
	VPSRLQ       $0x3a, Y1, Y1
	VPSRLQ       $0x27, Y2, Y2
	VPSRLQ       $0x38, Y3, Y3
	VPSRLQ       $0x2e, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 320(AX)
	VMOVDQU      Y6, 352(AX)
	VMOVDQU      Y7, 384(AX)
	VMOVDQU      Y8, 416(AX)
	VMOVDQU      Y9, 448(AX)
	VPXOR        608(AX), Y14, Y0
	VPXOR        480(AX), Y10, Y1
	VPXOR        512(AX), Y11, Y2
	VPXOR        544(AX), Y12, Y3
	VPXOR        576(AX), Y13, Y4
	VPSLLQ       $0x1b, Y0, Y5
	VPSLLQ       $0x24, Y1, Y6
	VPSLLQ       $0x0a, Y2, Y7
	VPSLLQ       $0x0f, Y3, Y8
	VPSLLQ       $0x38, Y4, Y9
	VPSRLQ       $0x25, Y0, Y0
	VPSRLQ       $0x1c, Y1, Y1
	VPSRLQ       $0x36, Y2, Y2
	VPSRLQ       $0x31, Y3, Y3
	VPSRLQ       $0x08, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 480(AX)
	VMOVDQU      Y6, 512(AX)
	VMOVDQU      Y7, 544(AX)
	VMOVDQU      Y8, 576(AX)
	VMOVDQU      Y9, 608(AX)
	VPXOR        704(AX), Y12, Y0
	VPXOR        736(AX), Y13, Y1
	VPXOR        768(AX), Y14, Y2
	VPXOR        640(AX), Y10, Y3
	VPXOR        672(AX), Y11, Y4
	VPSLLQ       $0x3e, Y0, Y5
	VPSLLQ       $0x37, Y1, Y6
	VPSLLQ       $0x27, Y2, Y7
	VPSLLQ       $0x29, Y3, Y8
	VPSLLQ       $0x02, Y4, Y9
	VPSRLQ       $0x02, Y0, Y0
	VPSRLQ       $0x09, Y1, Y1
	VPSRLQ       $0x19, Y2, Y2
	VPSRLQ       $0x17, Y3, Y3
	VPSRLQ       $0x3e, Y4, Y4
	VPOR         Y5, Y0, Y0
	VPOR         Y6, Y1, Y1
	VPOR         Y7, Y2, Y2
	VPOR         Y8, Y3, Y3
	VPOR         Y9, Y4, Y4
	VPANDN       Y2, Y1, Y5
	VPANDN       Y3, Y2, Y6
	VPANDN       Y4, Y3, Y7
	VPANDN       Y0, Y4, Y8
	VPANDN       Y1, Y0, Y9
	VPXOR        Y0, Y5, Y5
	VPXOR        Y1, Y6, Y6
	VPXOR        Y2, Y7, Y7
	VPXOR        Y3, Y8, Y8
	VPXOR        Y4, Y9, Y9
	VMOVDQU      Y5, 640(AX)
	VMOVDQU      Y6, 672(AX)
	VMOVDQU      Y7, 704(AX)
	VMOVDQU      Y8, 736(AX)
	VMOVDQU      Y9, 768(AX)
	ADDQ         $0x20, CX
	SUBQ         $0x00000001, DX
	JNZ          loop
	RET

DATA rc<>+0(SB)/8, $0x0000000000000001
DATA rc<>+8(SB)/8, $0x0000000000008082
DATA rc<>+16(SB)/8, $0x800000000000808a
DATA rc<>+24(SB)/8, $0x8000000080008000
DATA rc<>+32(SB)/8, $0x000000000000808b
DATA rc<>+40(SB)/8, $0x0000000080000001
DATA rc<>+48(SB)/8, $0x8000000080008081
DATA rc<>+56(SB)/8, $0x8000000000008009
DATA rc<>+64(SB)/8, $0x000000000000008a
DATA rc<>+72(SB)/8, $0x0000000000000088
DATA rc<>+80(SB)/8, $0x0000000080008009
DATA rc<>+88(SB)/8, $0x000000008000000a
DATA rc<>+96(SB)/8, $0x000000008000808b
DATA rc<>+104(SB)/8, $0x800000000000008b
DATA rc<>+112(SB)/8, $0x8000000000008089
DATA rc<>+120(SB)/8, $0x8000000000008003
DATA rc<>+128(SB)/8, $0x8000000000008002
DATA rc<>+136(SB)/8, $0x8000000000000080
DATA rc<>+144(SB)/8, $0x000000000000800a
DATA rc<>+152(SB)/8, $0x800000008000000a
DATA rc<>+160(SB)/8, $0x8000000080008081
DATA rc<>+168(SB)/8, $0x8000000000008080
DATA rc<>+176(SB)/8, $0x0000000080000001
DATA rc<>+184(SB)/8, $0x8000000080008008
GLOBL rc<>(SB), RODATA|NOPTR, $192
